PUT http://localhost:8080/api/transacao/atualizar/2
Content-Type: application/json

{
  "descricao": "Tranferencia pro modolo me dar 10",
  "valor": 6969.69,
  "data_transacao": "2023-09-01",
  "tipo_transacao": "transferencia"
}
